name: Arduino Build Check
on:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Compile sketch for Arduino UNO
              uses: arduino/compile-sketches@v1
              with:
                  fqbn: arduino:avr:nano:cpu=atmega328old
                  sketch-paths: |
                      ./arduino-nano

            - name: Find firmware files
              run: |
                  find . -name "*.hex" -o -name "*.elf" -o -name "*.bin"

            - name: Upload compiled firmware
              uses: actions/upload-artifact@v4
              with:
                  name: nano-firmware-bin
                  path: build/**/*.hex